### ISSUE TITLE
Autograde does not run on notebooks with names different from assignment name or released notebook

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/abc-classroom#88] opened 2019-09-30 21:35 UTC
Currently, `nbgrader autograde <assignment_name>` only executes on notebooks with names that exactly match the name of the assignment or released notebook (e.g. assignment = `ea-bootcamp-00-test-assignment` | released notebook = `ea-bootcamp-00-test-assignment.ipynb`). 

Renamed assignment notebooks (e.g.  `ea-bootcamp-00-test-assignment-student-name.ipynb`) are successfully pulled down into the `submitted` directory by the `clone-all.py` script.  However, these renamed notebooks are not autograded by `nbgrader autograde <assignment_name>`. Thus, these renamed notebook are not copied to the `autograded` directory and do not show up in the manual grading tab of the nbgrader GUI.  

We would like to have `nbgrader autograde <assignment_name>` run on these renamed notebooks.   For now, students are asked not to rename the assignment notebook.

**Comment by kcranston** [comment] 2019-10-01 14:39
Hmm... according to the [nbgrader docs](https://nbgrader.readthedocs.io/en/stable/user_guide/creating_and_grading_assignments.html#autograde-assignments), autograde should run on all of the notebooks in the directory (assuming the path is `submitted/student_name/assignment_name`). I'll try and reproduce locally.

**Comment by lwasser** [comment] 2019-10-01 15:44
@kcranston i think this issue can wait. i'd rather you work on the abc-classroom issues i scoped out! this issue is specific. it's when a student renames the notebook and we'd like to ehnance the functionality to allow them to rename in the FUTURE

**Comment by lwasser** [comment] 2019-10-01 15:45
i've created several issues that i'd like for you to address first in this effort!! this was actually an enhancement that jenny and i discussed that we'd like to implement for the future. the fix for now is to tell the students to NOT rename the assignments

**Comment by lwasser** [comment] 2020-12-02 00:39
i think the issue is that you have to have a release notebook and source notebook for any notebook a student submits. that is how nbgrader knows what notebook to use to grade the student notebook. it would be nie if you could add a name to the end of the notebook name but that is just not how nbgrader works. i'm going to close this for the time being because it's how nbgrader works!

**Closed by lwasser** 2020-12-02 00:39 UTC
